-- Schema do Cardápio Digital - já aplicado no projeto Supabase.
-- Região: sa-east-1
-- Projeto: kyzptazmxfkkhncjpuzy

create table if not exists public.produtos (
  id text primary key, nome text not null, descricao text not null,
  preco numeric(10,2) not null check (preco >= 0),
  categoria text not null check (categoria in ('ENTRADAS','PRATO PRINCIPAL','SOBREMESAS','BEBIDAS','CARTA DE VINHOS')),
  imagem text
);
create table if not exists public.pedidos (
  id bigint generated by default as identity primary key, numero_pedido text unique not null,
  nome_cliente text not null, mesa integer not null check (mesa > 0),
  subtotal numeric(10,2) not null check (subtotal >= 0), taxa_garcom numeric(10,2) not null default 0 check (taxa_garcom >= 0),
  total numeric(10,2) not null check (total >= 0), status text not null default 'NOVO' check (status in ('NOVO','PREPARANDO','PRONTO','ENTREGUE','CANCELADO')),
  criado_em timestamptz not null default now()
);
create table if not exists public.itens_pedido (
  id bigint generated by default as identity primary key, pedido_id bigint not null references public.pedidos(id) on delete cascade,
  produto_id text not null references public.produtos(id), nome_produto text not null, quantidade integer not null check (quantidade > 0),
  valor_unitario numeric(10,2) not null check (valor_unitario >= 0), valor_total numeric(10,2) not null check (valor_total >= 0)
);

-- Índices
create index if not exists idx_produtos_categoria on public.produtos(categoria);
create index if not exists idx_produtos_nome on public.produtos(nome);
create index if not exists idx_pedidos_criado_em on public.pedidos(criado_em desc);
create index if not exists idx_pedidos_status on public.pedidos(status);
create index if not exists idx_itens_pedido_pedido_id on public.itens_pedido(pedido_id);
create index if not exists idx_itens_pedido_produto_id on public.itens_pedido(produto_id);

-- Segurança
alter table public.produtos enable row level security;
alter table public.pedidos enable row level security;
alter table public.itens_pedido enable row level security;
grant select on public.produtos to anon, authenticated;
grant select, insert, update, delete on public.produtos to authenticated;
grant select, insert on public.pedidos to anon, authenticated;
grant select, insert on public.itens_pedido to anon, authenticated;
grant update on public.pedidos to authenticated;
grant update, delete on public.itens_pedido to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Políticas
create policy "Cardapio publico pode ler produtos" on public.produtos for select to anon, authenticated using (true);
create policy "Clientes podem criar pedidos" on public.pedidos for insert to anon, authenticated with check (mesa > 0 and subtotal >= 0 and taxa_garcom >= 0 and total >= 0);
create policy "Clientes podem ler pedidos" on public.pedidos for select to anon, authenticated using (true);
create policy "Clientes podem criar itens" on public.itens_pedido for insert to anon, authenticated with check (quantidade > 0 and valor_unitario >= 0 and valor_total >= 0);
create policy "Clientes podem ler itens" on public.itens_pedido for select to anon, authenticated using (true);
create policy "Autenticados podem atualizar pedidos" on public.pedidos for update to authenticated using (true) with check (true);
create policy "Autenticados podem atualizar itens" on public.itens_pedido for update to authenticated using (true) with check (true);
create policy "Autenticados podem apagar itens" on public.itens_pedido for delete to authenticated using (true);

-- Realtime
alter publication supabase_realtime add table public.pedidos;
